export const items = [
  "alert",
  "archive",
  "award",
  "ban",
  "bell",
  "book",
  "bookmark",
  "box",
  "calendar",
  "camera",
  "clock",
  "cloud",
  "code",
  "cog",
  "compass",
  "crosshair",
  "document",
  "draw",
  "drop",
  "eye",
  "help",
	"heart",
  "idea",
  "issue",
  "image",
  "inbox",
  "key",
  "film",
  "lock",
  "mail",
  "marker",
  "music",
  "paperclip",
  "phone",
  "pulse",
  "star",
  "tag",
  "tool",
  "user",
  "users",
  "video",
  "youtube",
];

let lookup: string[2]; 

export var icon_lookup = {
  "alert": ["warning-sign","alert-triangle"],
  "archive": ["archive","archive"],
  "award": ["endorsed","award"],
  "ban": ["ban-circle", "slash"],
  "bell": ["notifications", "bell"],
  "book": ["book", "book"],
  bookmark: ["bookmark", "bookmark"],
  box: ["box", "package"],
  calendar: ["calendar", "calendar"],
  camera: ["camera", "camera"],
  clock: ["time", "clock"],
  cloud: ["cloud", "cloud"],
  code: ["code-block", "code"],
  cog: ["cog", "settings"],
  compass: ["compass", "compass"],
  crosshair: ["locate", "crosshair"],
  document: ["document", "file"],
  draw: ["draw", "pen-tool"],
  drop: ["tint", "droplet"],
  eye: ["eye-open", "eye"],
	heart: ["heart", "heart"],
  help: ["help", "help-circle"],
  idea: ["lightbulb", "zap"],
  issue: ["issue", "alert-circle"],
  image: ["media", "image"],
  inbox: ["inbox", "inbox"],
  key: ["key", "key"],
  film: ["film", "film"],
  lock: ["lock", "lock"],
  mail: ["envelope", "mail"],
  marker: ["map-marker", "map-pin"],
  music: ["music", "music"],
  paperclip: ["paperclip", "paperclip"],
  phone: ["phone", "phone"],
  pulse: ["pulse", "activity"],
  star: ["star", "star"],
  tag: ["tag", "tag"],
  tool: ["build", "tool"],
  user: ["user", "user"],
  users: ["people", "users"],
  video: ["mobile video", "video"],
  "youtube": ["video","youtube"],
};
