export const items = [
    "alert",
    "archive",
    "arrow-bottom-left",
    "arrow-bottom-right",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-top-left",
    "arrow-top-right",
    "arrow-up",
    "award",
    "ban",
    "bell",
    "book",
    "bookmark",
    "box",
    "briefcase",
    "calendar",
    "camera",
    "chat",
    "check",
    "circle-arrow-down",
    "circle-arrow-left",
    "circle-arrow-right",
    "circle-arrow-up",
    "clock",
    "cloud",
    "chevron-left",
    "chevron-right",
    "code",
    "cog",
    "compass",
    "credit-card",
    "cross",
    "crosshair",
    "document",
    "draw",
    "drop",
    "eye",
    "github",
    "gitlab",
    "help",
    "heart",
    "idea",
    "issue",
    "image",
    "inbox",
    "key",
    "linkedin",
    "film",
    "folder",
    "lock",
    "mail",
    "marker",
    "mobile",
    "music",
    "paperclip",
    "phone",
    "pulse",
    "slack",
    "star",
    "tag",
    "tool",
    "user",
    "users",
    "video",
    "youtube",
];

export var icon_lookup = {
  alert: ["warning-sign", "alert-triangle"],
  archive: ["archive", "archive"],
  "arrow-bottom-left": ["arrow-bottom-left", "arrow-down-left"],
  "arrow-bottom-right": ["arrow-bottom-right", "arrow-down-right"],
  "arrow-down": ["arrow-down", "arrow-down"],
  "arrow-left": ["arrow-left", "arrow-left"],
  "arrow-right": ["arrow-right", "arrow-right"],
  "arrow-top-left": ["arrow-top-left", "arrow-up-left"],
  "arrow-top-right": ["arrow-top-right", "arrow-up-right"],
  "arrow-up": ["arrow-up", "arrow-up"],
  award: ["endorsed", "award"],
  ban: ["ban-circle", "slash"],
  bell: ["notifications", "bell"],
  book: ["book", "book"],
  bookmark: ["bookmark", "bookmark"],
  box: ["box", "package"],
  briefcase:  ["briefcase", "briefcase"],
  calendar: ["calendar", "calendar"],
  camera: ["camera", "camera"],
  clock: ["time", "clock"],
  cloud: ["cloud", "cloud"],
    chat: ["chat", "message-square"],
  check: ["tick", "check"],
  "check-cirle": ["tick-circle", "check-circle"],
  "chevron-left": ["chevron-left","chevron-left"],
  "chevron-right": ["chevron-right","chevron-right"],
  "circle-arrow-down": ["circle-arrow-down", "arrow-down-circle"],
  "circle-arrow-left": ["circle-arrow-left", "arrow-left-circle"],
  "circle-arrow-right": ["circle-arrow-right", "arrow-right-circle"],
  "circle-arrow-up": ["circle-arrow-up", "arrow-up-circle"],
  code: ["code-block", "code"],
  cog: ["cog", "settings"],
  compass: ["compass", "compass"],
  "credit-card": ["credit-card", "credit-card"],
  cross: ["delete", "x-circle"],
  crosshair: ["locate", "crosshair"],
  document: ["document", "file"],
  draw: ["draw", "pen-tool"],
  drop: ["tint", "droplet"],
  eye: ["eye-open", "eye"],
  github: ["git-repo", "github"],
  gitlab: ["git-repo", "gitlab"],
  heart: ["heart", "heart"],
  help: ["help", "help-circle"],
  idea: ["lightbulb", "zap"],
  issue: ["issue", "alert-circle"],
  image: ["media", "image"],
  inbox: ["inbox", "inbox"],
  key: ["key", "key"],
  film: ["film", "film"],
  folder: ["folder-close", "folder"],
  linkedin: ["id-number", "linkedin"],
  lock: ["lock", "lock"],
  mail: ["envelope", "mail"],
  marker: ["map-marker", "map-pin"],
  mobile: ["mobile-phone", "smartphone"],
  music: ["music", "music"],
  paperclip: ["paperclip", "paperclip"],
  phone: ["phone", "phone"],
  pulse: ["pulse", "activity"],
  slack: ["social-media", "slack"],
  star: ["star", "star"],
  tag: ["tag", "tag"],
  tool: ["build", "tool"],
  user: ["user", "user"],
  users: ["people", "users"],
  video: ["mobile-video", "video"],
  youtube: ["video", "youtube"],
};
